## Домашнее задание



### 1. Локализация корней.

Локализовать действительные корни в уравнении:

$$
f(x)=20 x^{3} - 4 x^{2} - 5 x + 1 .
$$

$\left|a_{n}\right|$ = 1
$\left|a_{0}\right|$ = 20

A = 5

B = 20

$\frac{1}{21} \leq \left|x_{0}\right| \leq \frac{5}{4}$

### 2. Порядок сходимости итерационного метода.

Определить порядок сходимости итерационного метода при вычислении квадратного корня $x^* = \sqrt a$ :



$$
x_{n+1}=x_n - \frac{11x_n^4 - 4x_n^2 a + a^2}{16 x_n^5} (x_n^2 - a)
$$

Сдавал, как летучку



### 3. Метод Ньютона и Гаусса-Ньютона.

Решение проблемы многомерной линейной регрессии нормальным уравнением очень похоже на обобщение метода Ньютона на многомерный случай. Но это не так.
Укажите, в чём различие между методами. В одномерном случае

$$
f(x) \approx f(x_0) + f^{\prime}(x_0)(x - x_0) = 0
$$

$$
x =  x_0 - \frac{f(x_0)}{f^{\prime}(x_0)}
$$

Обобщение метода Ньютона на многомерный случай выглядит так.

$$
F(\vec{β}) \approx F(\vec{β^{(0)}}) + \sum\limits_{i=1}^n{\frac{∂F(\vec{β^{(0)}})}{∂β_i}(β_i - β^0_i)} = 0
$$

$$
F(\vec{β^{(0)}}) + \nabla F(\vec{β^{(0)}})\vec{p}   = 0
$$

В случае поиска минимума функции F к нулю приравниваем частные производные F
$$
\frac{∂F(\vec{β})}{∂β_i} \approx \frac{∂F(\vec{β^{(0)}})}{∂β_i} + \sum\limits_{j=1}^n{\frac{∂^2F(\vec{β^{(0)}})}{∂β_i∂β_j}(β_i - β^0_i)} = 0
$$

Хинт: покажите, что

$$
2J^TJ  \neq   H_{ij}
$$

$H_{ij}$ - гессиан F.


Метод Ньютона для многомерного случая

Метод Ньютона расширяется на многомерный случай, предполагая, что мы имеем систему уравнений, которые нужно решить. Для многомерного метода Ньютона мы вычисляем градиент $ \nabla F(\beta^{(0)})$  и Гессиан  $H_{ij} = \frac{\partial^2 F(\beta^{(0)})}{\partial \beta_i \partial \beta_j}$  функции  F . Это позволяет более точно перемещаться к минимуму функции, учитывая кривизну функции, которую описывает гессиан. В этом случае обновление параметров выглядит так:


$\beta^{(1)} = \beta^{(0)} - H^{-1} \nabla F(\beta^{(0)})$


Метод Гаусса-Ньютона

Метод Гаусса-Ньютона, напротив, является аппроксимацией метода Ньютона и обычно используется для задач нелинейной наименьших квадратов, таких как многомерная линейная регрессия. Вместо гессиана, который может быть сложным и ресурсоемким для вычисления, метод Гаусса-Ньютона использует приближение, основанное на матричном якобиане  J  функции  F  для вычисления параметров. Аппроксимация гессиана при этом выглядит как:


$H \approx 2 J^T J$


где  J  — якобиан функции  F  по параметрам  $\beta$ . Заметим, что $ 2J^T J \neq H $ — это только приближение, что является основным различием между методами.


### 4. Зри в корень

Отделить корни следующих уравнений, а затем уточнить один из них с помощью подходящего итерационно процесса (любых двух на ваш выбор двумя разными методами):


a) $(0.5)^x+1=(x-1)^2$,

__b)__ $(x-3) \cos x=1, \quad-2 \pi \leq \mathrm{x} \leq 2 \pi$,

c) $\operatorname{arctg}(x-1)+2 x=0$,

__d)__ $x^2-20 \sin x=0$

e) $2 \operatorname{tg} x-x / 2+1=0$,

__f)__ $2 \lg x-x / 2+1=0$,

g) $x^2-e^x / 5=0$

__h)__ $\ln x+(x-1)^3=0$,

i) $x 2^x=1$

__j)__ $(x+1)^{0.5}=1 / x$.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import bisect, newton

# Определим функции для уравнений i и e
def f_i(x):
    return x * 2**x - 1

def f_i_prime(x):
    return 2**x * (1 + x * np.log(2))

def f_e(x):
    return 2 * np.tan(x) - x / 2 + 1

interval_i = (0, 1)  # Для уравнения i, очевидно, корень лежит между 0 и 1
interval_e = (-1, 1)  # Для уравнения e выберем интервал, избегая разрывов тангенса

# Найдем корни методом дихотомии
root_i_bisect = bisect(f_i, *interval_i)
root_e_bisect = bisect(f_e, *interval_e)

# Найдем корни методом Ньютона
root_i_newton = newton(f_i, x0=0.5, fprime=f_i_prime)  # начальная точка для i около 0.5
root_e_newton = newton(f_e, x0=0.5)  # начальная точка для e около 0.5, но избегаем близости к разрывам

root_i_bisect, root_i_newton, root_e_bisect, root_e_newton

(0.641185744503673,
 0.641185744504986,
 -0.5713179028334707,
 -0.5713179028318801)

### 5. Зри в корень дважды

Вычислить с точностью $\varepsilon=10^{-3}$ координаты точек пересечения кривых (любых двух на ваш выбор двумя разными методами):

a)
$$
\left\{\begin{array}{l}
\sin (x+1)-y=1.2 \\
2 x+\cos (y)=2
\end{array}\right.
$$
б)
$$
\left\{\begin{array}{l}
\tan (x y+0.4)=x^2 \\
0.6 x^2+2 y^2=1
\end{array}\right.
$$
B)
$$
\left\{\begin{array}{l}
\cos (x-1)+y=0.5 \\
x-\cos (y)=3
\end{array}\right.
$$
г)
$$
\left\{\begin{array}{l}
\sin (x+2)-y=1.5 \\
x+\cos (y-2)=0.5
\end{array}\right.
$$

In [3]:
from scipy.optimize import fsolve

# Выберем а) и г)
epsilon = 1e-3

def system_a(vars):
    x, y = vars
    return [np.sin(x + 1) - y - 1.2, 2 * x + np.cos(y) - 2]

def system_g(vars):
    x, y = vars
    return [np.sin(x + 2) - y - 1.5, x + np.cos(y - 2) - 0.5]

# Начальные приближения для каждой системы
initial_guess_a = (0, 0)
initial_guess_g = (0, 0)



solution_a_1 = fsolve(system_a, initial_guess_a, xtol=epsilon)
solution_a_2 = fsolve(system_a, (1, 1), xtol=epsilon)  # Другое начальное приближение


solution_g_1 = fsolve(system_g, initial_guess_g, xtol=epsilon)
solution_g_2 = fsolve(system_g, (1, 1), xtol=epsilon)  # Другое начальное приближение

solution_a_1, solution_a_2, solution_g_1, solution_g_2

(array([ 0.5101495 , -0.20183784]),
 array([ 0.51015013, -0.2018384 ]),
 array([ 1.34633741, -1.70331696]),
 array([ 1.34636874, -1.70336398]))

### 6*. Оценка скорости сходимости метода Ньютона.
Покажите, что для функции $f(x)=|x|^{5 / 2}$ метод Ньютона сходится лишь экспонциально - т.е. невязка уменьшается пропорционально $e^{-n}$.

Покажите аналитически, что метод Ньютона в лучшем случае имеет квадратичную экспонциальную сходимость, т.е. ошибка убывает пропорционально $e^{-n^2}$.




$f(x) = |x|^{5/2}$ , найдем первую производную:

$f{\prime}(x) = \frac{5}{2} \, |x|^{3/2} \, \operatorname{sgn}(x)$


Применение формулы Ньютона

При малых значениях  x ,  f(x)  и  $f{\prime}(x) $ также малы, что замедляет сходимость. Для  x_n  достаточно близкого к нулю:

$x_{n+1} = x_n - \frac{|x_n|^{5/2}}{\frac{5}{2} |x_n|^{3/2} \operatorname{sgn}(x_n)} = x_n - \frac{2}{5} |x_n| = \left(1 - \frac{2}{5}\right) x_n = \frac{3}{5} x_n$

Это показывает, что:

$|x_{n+1}| = \frac{3}{5} |x_n|$


Таким образом, на каждом шаге  $|x_n| $ уменьшается в геометрической прогрессии с коэффициентом $ \frac{3}{5} $, что указывает на экспоненциальную сходимость:

$|x_n| \approx \left(\frac{3}{5}\right)^n x_0$

и ошибка убывает пропорционально $ e^{-n} $.
