In [1]:
import numpy as np

__Задание 1. Генератор случайных матриц.__

Реализовать генератор матриц, который должен поддерживать функции:
* Генерация абсолютно случайной матрицы $n\times m$
* Генерация случайной диагональной матрицы $n\times n$
* Генерация случайной верхнетреугольной матрицы
* Генерация случайной нижнетреугольной матрицы
* Генерация симметричной матрицы
* Генерация возмущения матрицы $n\times m$, каждый элемент которой не превосходит по модулю заданный $\varepsilon$. Оценить величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).

Оценить численно вероятность того, что созданная матрица будет вырожденной для какого-либо случая выше.

In [3]:

def matrix_generate(rows, columns, type_ = "full", eps = 0):
    A = None

    if type_ == "full":
        A = np.random.random(size=(rows, columns))

    elif type_ == "upper_triangular":
        A = np.triu(np.random.random(size=(rows, columns)))

    elif type_ == "lower_triangular":
        A = np.tril(np.random.random(size=(rows, columns)))

    elif type_ == "symmetric":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.random.random(size=(rows, columns))
            A = (A + A.T) / 2

    elif type_ == "diagonal":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.diag(np.random.random(size=rows))

    elif type_ == "perturbation":
        A = np.random.uniform(-eps, eps, size=(rows, columns))
        

    else:
        return f"Error with type {type_} and shape ({rows},{columns})"

    return A

In [4]:
matrix_generate(1, 3)

array([[0.35992462, 0.79451555, 0.09555595]])

In [5]:
matrix_generate(4, 4, type_ = "diagonal")

array([[0.77917945, 0.        , 0.        , 0.        ],
       [0.        , 0.41425724, 0.        , 0.        ],
       [0.        , 0.        , 0.22794092, 0.        ],
       [0.        , 0.        , 0.        , 0.2695036 ]])

In [6]:
matrix_generate(4, 4, type_ = "upper_triangular")

array([[0.61452128, 0.34820629, 0.16720591, 0.37846151],
       [0.        , 0.20015628, 0.70622661, 0.72677347],
       [0.        , 0.        , 0.44891598, 0.86842141],
       [0.        , 0.        , 0.        , 0.9911288 ]])

In [7]:
matrix_generate(4, 4, type_ = "lower_triangular")

array([[0.24009932, 0.        , 0.        , 0.        ],
       [0.49832008, 0.12657328, 0.        , 0.        ],
       [0.31101872, 0.38788159, 0.88760546, 0.        ],
       [0.46644499, 0.16433465, 0.74620298, 0.9451514 ]])

In [8]:
matrix_generate(4, 4, type_ = "symmetric")

array([[0.27633372, 0.07395469, 0.56785259, 0.52679554],
       [0.07395469, 0.50570934, 0.84637788, 0.58443492],
       [0.56785259, 0.84637788, 0.25912268, 0.43178006],
       [0.52679554, 0.58443492, 0.43178006, 0.95314766]])

In [9]:
matrix_generate(4, 1, type_ = "symmetric")

'Error with type symmetric and shape (4,1)'

Теперь величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).



- __Норма Фробениуса__:  $\quad$   $||M||_F=\sqrt{\sum_{i=1}^n \sum_{j=1}^n\left|a_{i j}\right|^2} \leq \sqrt{nm} \varepsilon$

#### Задание 2. Вычисление матричных норм и числа обусловленности.

Реализовать вычисление трех основных норм векторов (L1, L2 и максимальную) и подчиненных им матричных норм. Реализовать вычисление числа обусловленности.

Примечание: для вычисления собственных значений можно использовать linalg.eigvals из модуля scipy.

In [11]:
def vec_norm(v, type_ = "M"):

    if type_ == "M":
        return np.max(np.abs(v))
    
    elif type_ == "l1":
        return np.sum(np.abs(v))
    
    elif type_ == "l2":
        return np.sqrt(np.sum((np.abs(v))**2))
    
    else:
        return f"Error: no type {type_}"
    

def mat_norm(m, type_ = "M"):

    if type_ == "M":
        return np.max(np.sum(np.abs(m), axis=1))
    
    elif type_ == "l1":
        return np.max(np.sum(np.abs(m), axis=0))
    
    elif type_ == "l2":
        eigenvalues, _ = np.linalg.eig(np.dot(m.T, m))
        return np.sqrt(np.max(eigenvalues))

    else:
        return f"Error: no type {type_}"
    

def condition_number(m, type_ = "M"):
    norm_m = mat_norm(m, type_)
    
    try:
        inv_m = np.linalg.inv(m)
        norm_inv_m = mat_norm(inv_m, type_)
    except np.linalg.LinAlgError:
        raise ValueError("Error: the matrix is singular and has no inverse")
    
    condition_num = norm_m * norm_inv_m
    return condition_num      

In [12]:
M = np.array([[1, 2], [3, 4]])

print(mat_norm(M, type_ = "M"))
print(np.linalg.norm(M, ord=np.inf))

7
7.0


In [13]:
M = np.array([[1, 2], [3, 4]])

print(mat_norm(M, type_ = "l1"))
print(np.linalg.norm(M, ord=1))

6
6.0


In [14]:
M = np.array([[1, 2], [3, 4]])

print(mat_norm(M, type_ = "l2"))
print(np.linalg.norm(M, ord=2))

5.464985704219043
5.464985704219043


In [18]:
print("Condition number of matrix M:", condition_number(M, type_='l2'))

Condition number of matrix M: 14.93303437365925


#### Задание 3. Эквивалентность первых двух норм

Найдите константы $C_1$  и  $C_2$ такие, что

$\ C_1||\mathbf{x}||_2\leq||\mathbf{x}||_1\leq C_2||\mathbf{x}||_2$

__________________________________________

Для вектора $\mathbf{x} \in \mathbb{R}^n$:

- Норма $\ell_1$ определена как:
  $ ||\mathbf{x}||_1 = \sum_{i=1}^n |x_i|$

- Норма $\ell_2$ определена как:
  $ ||\mathbf{x}||_2 = \sqrt{\sum_{i=1}^n x_i^2} $

Теперь найдём константы $C_1$ и $C_2$, такие что:
$ C_1 ||\mathbf{x}||_2 \leq ||\mathbf{x}||_1 \leq C_2 ||\mathbf{x}||_2 $

Для любого вектора  $\mathbf{x}$  из  $\mathbb{R}^n$  применим неравенство Коши-Буняковского:


$||\mathbf{x}||1 = \left( \sum_{i=1}^{n} |x_i| \right)  \leq \sqrt{n} \left( \sum_{i=1}^{n} x_i^2 \right)^{1/2} = \sqrt{n} ||\mathbf{x}||_2.$


Отсюда:


$||\mathbf{x}||_1 \leq \sqrt{n} ||\mathbf{x}||_2,$


то есть  C_2 = $\sqrt{n} .$

Для $\ C_1||\mathbf{x}||_2\leq||\mathbf{x}||_1$

Очевидно, подойдет $С_1 = 1$

#### Задание 4. Евклидова и бесконечная норма.

 Пусть x — вектор размерности m, а A — матрица m×n. Докажите следующие неравенства и приведите
примеры таких x и A, при которых неравенства обращаются в равенства:

- $||x||_2 \leq \sqrt{m} \cdot ||x||_{\infty}$
- $||A||_{\infty} \leq \sqrt{n} \cdot ||A||_2$

__________________________

**1. Неравенство** $||x||_2 \leq \sqrt{m} \cdot ||x||_{\infty}$

***Доказательство:***

Воспользуемся определением норм. Пусть $x = (x_1, x_2, \ldots, x_m)$.

- Норма $\ell_2$:
  $ ||x||_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_m^2} $

- Норма $\ell_{\infty}$:
  $ ||x||_{\infty} = \max_{1 \leq i \leq m} |x_i| $

Пусть $M = ||x||_{\infty}$. Тогда $|x_i| \leq M \quad \forall i$, значит:
$ x_1^2 + x_2^2 + \ldots + x_m^2 \leq m M^2 $

Следовательно:
$ ||x||_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_m^2} \leq \sqrt{m M^2} = \sqrt{m} \cdot ||x||_{\infty} $

Таким образом:
$ ||x||_2 \leq \sqrt{m} \cdot ||x||_{\infty} $

***Пример:***

Рассмотрим вектор $x = (1, 1, \ldots, 1)$ размерности $m$. В этом случае:
$ ||x||_2 = \sqrt{m} \quad \text{и} \quad ||x||_{\infty} = 1 $  
Подставляя в неравенство, получаем:  
$ ||x||_2 = \sqrt{m} \leq \sqrt{m} \cdot 1 $  
что дает равенство $||x||_2 = \sqrt{m} \cdot ||x||_{\infty}$.

**2. Неравенство** $||A||_{\infty} \leq \sqrt{n} \cdot ||A||_2$

***Доказательство:***

Из теории и матанализа нам известно, что:  
$ ||A||_{\infty} = \sup_{x \neq 0} \dfrac{||Ax||_{\infty}}{||x||_{\infty}} \leq \sup_{x \neq 0} \dfrac{||Ax||_{\infty}}{\dfrac{1}{\sqrt{n}}||x||_{2}} \leq \sup_{x \neq 0} \dfrac{\sqrt{n} \cdot ||Ax||_{2}}{\sqrt{m} \cdot ||x||_{2}} \leq \sqrt{n} \cdot ||A||_{2}$

Откуда:
$ ||A||_{\infty} \leq \sqrt{n} \cdot ||A||_2 $  

***Пример:***

Рассмотрим матрицу $A = \begin{pmatrix} 1 & 1 & 1 & \dots & 1 \\ 0 & \dots & \dots & \dots & 0 \\ \vdots & \vdots & \vdots & \vdots & \vdots \\ 0 & \dots & \dots & \dots & 0 \end{pmatrix}$ размерности $m \times n$. В этом случае:
- Норма $||A||_{\infty} = n$.  
- Норма $||A||_2 = \sqrt{n}$.

Таким образом, получаем:
$ ||A||_{\infty} = n = \sqrt{n} \cdot \sqrt{n} = \sqrt{n} \cdot ||A||_{2}$.  

____________________

#### Задание 5.  Норма Фробениуса.

Докажите, что для любой унитарной матрицы U (и для произвольной матрицы A) имеет место равенство

 $\| U A \|_F = \| AU \|_F = \| A \|_F$ ,

 где $\| \cdot \|_F$ — норма Фробениуса.

Указание.  
Задачу можно решить без вычислений, если использовать геометрический смысл нормы Фробениуса и геометрические свойства умножения  
на унитарную матрицу (что при умножении на неё сохраняется).

____________________

$||\mathbf{A}||_{F}^{2}=\operatorname{tr} (\mathbf{A}^{+} \mathbf{A}) = \operatorname{tr} (\mathbf{A} \mathbf{A}^{+})$  

$||\mathbf{UA}||_{F}^{2}=\operatorname{tr} (\mathbf{A}^{+} \mathbf{U}^{+} \mathbf{U} \mathbf{A} ) = \operatorname{tr} (\mathbf{A}^{+} \mathbf{A}) = ||\mathbf{A}||_{F}^{2}$  

$||\mathbf{AU}||_{F}^{2}=\operatorname{tr} (\mathbf{A} \mathbf{U} \mathbf{U}^{+} \mathbf{A}^{+}) = \operatorname{tr} (\mathbf{A} \mathbf{A}^{+}) = ||\mathbf{A}||_{F}^{2}$  

что и требовалось доказать